# Generated by Django 3.1.4 on 2020-12-24 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='due',
        ),
    ]
