# Generated by Django 3.1.4 on 2020-12-28 20:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_remove_account_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='due',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=45),
            preserve_default=False,
        ),
    ]
